language: android
sudo: false
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    - build-tools-23.0.2

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-23
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-23
    # Emulator Management: Create, Start and Wait
    # Handle git submodules yourself

licenses:
    - '.+'

git:
    submodules: false
before_install:
	- echo "Remove unused android components to gain disk space and avoid related issues"; export IMGS=${ANDROID_HOME}system-images; rm -R ${IMGS}/android-15; rm -R ${IMGS}/android-16; rm -R ${IMGS}/android-17; rm -R ${IMGS}/android-18; export PFRM=${ANDROID_HOME}platforms; rm -R ${PFRM}/android-15; rm -R ${PFRM}/android-16; rm -R ${PFRM}/android-17; rm -R ${PFRM}/android-18; || true
before_script:
       - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
       - emulator -avd test -no-skin -no-audio -no-window &
       - android-wait-for-emulator
       - adb shell input keyevent 82 &
script:
      - ./gradlew clean build connectedCheck --stacktrace --info
